name: Patch Rebuild (Force Build)

on:
  workflow_dispatch:

jobs:
  pr-build:
    uses: genesis-ai-dev/codex/.github/workflows/pr-build.yml@feat/sideloader
    with:
      pr_number: '31'
    secrets: inherit
